# Site settings
title: BI Vu Consulting
email: info@BIVu.ca
description: > # this means to ignore newlines until "baseurl:"
  BI Vu Consulting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bivu.ca" # the base hostname & protocol for your site

twitter_username: vsembhi
LinkedIn_username: sembhi

# Build settings
markdown: kramdown
