version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
        - "4000:4000"
    volumes:
        - .:/srv/jekyll
    environment:
       - JEKYLL_ENV=stage
    command:  ./startup.sh

